import { ECalendarValue, IDatePickerConfig } from 'date-picker-ng';

export const DEF_CONF: IDatePickerConfig = {
  closeOnEnter: true,
  closeOnSelect: null,
  closeOnSelectDelay: 100,
  dayBtnFormat: 'DD',
  disableKeypress: false,
  enableMonthSelector: true,
  firstDayOfWeek: 'su',
  hideInputContainer: false,
  hideOnOutsideClick: true,
  hours12Format: 'hh',
  hours24Format: 'HH',
  meridiemFormat: 'A',
  minutesFormat: 'mm',
  minutesInterval: 1,
  monthBtnFormat: 'MMM',
  monthFormat: 'MMM, YYYY',
  multipleYearsNavigateBy: 10,
  numOfMonthRows: 3,
  onOpenDelay: 0,
  openOnClick: true,
  openOnFocus: true,
  returnedValueType: ECalendarValue.String,
  secondsFormat: 'ss',
  secondsInterval: 1,
  showGoToCurrent: true,
  showMultipleYearsNavigation: false,
  showNearMonthDays: true,
  showSeconds: false,
  showTwentyFourHours: false,
  showWeekNumbers: false,
  timeSeparator: ':',
  unSelectOnClick: true,
  weekDayFormat: 'ddd',
  yearFormat: 'YYYY',
};
